name: Create Work Item in Azure DevOps from Issue

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:
        github_token: 'temp'
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'privatepreview'
        ado_project: 'Agile 1'
        ado_wit: 'User Story' 
